name: sosit_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.9.1
  google_maps_flutter: ^2.12.3
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # BLE & Emergency Features
  flutter_blue_plus: ^1.30.7
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  #flutter_local_notifications: ^16.3.0
  #audioplayers: ^5.2.1
  #vibration: ^1.8.4
  url_launcher: ^6.2.2
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/