// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArXgE0rW0QikLQ3KzFs0p1HiKkBgf9SfE',
    appId: '1:454157407764:web:6c6f3bc638b0e767c8b901',
    messagingSenderId: '454157407764',
    projectId: 'sosit-dcaf0',
    authDomain: 'sosit-dcaf0.firebaseapp.com',
    storageBucket: 'sosit-dcaf0.firebasestorage.app',
    measurementId: 'G-TVMQK74NL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCgc2olRy2TqRakwPl_hKEHP9bGulQ64k',
    appId: '1:454157407764:android:ab8711d10063ab16c8b901',
    messagingSenderId: '454157407764',
    projectId: 'sosit-dcaf0',
    storageBucket: 'sosit-dcaf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCON402vj5aZ1W5tQYs7TSuhhooL7TKhY4',
    appId: '1:454157407764:ios:b45f7ae7d6031430c8b901',
    messagingSenderId: '454157407764',
    projectId: 'sosit-dcaf0',
    storageBucket: 'sosit-dcaf0.firebasestorage.app',
    iosBundleId: 'com.example.sositApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCON402vj5aZ1W5tQYs7TSuhhooL7TKhY4',
    appId: '1:454157407764:ios:b45f7ae7d6031430c8b901',
    messagingSenderId: '454157407764',
    projectId: 'sosit-dcaf0',
    storageBucket: 'sosit-dcaf0.firebasestorage.app',
    iosBundleId: 'com.example.sositApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArXgE0rW0QikLQ3KzFs0p1HiKkBgf9SfE',
    appId: '1:454157407764:web:4760a674ebfebfc1c8b901',
    messagingSenderId: '454157407764',
    projectId: 'sosit-dcaf0',
    authDomain: 'sosit-dcaf0.firebaseapp.com',
    storageBucket: 'sosit-dcaf0.firebasestorage.app',
    measurementId: 'G-8HPJLSS4W4',
  );
}
